version: '3.7'
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:2.9.21'
    container_name: 'nginx-proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy_manager

  db:
    image: mysql
    volumes:
      - "./db.sqllite3:/var/lib/mysql/"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
      - MYSQL_HOST=''
    networks:
      - proxy_manager

  web:
    build: .
    command: bash -c "./manage.py collectstatic --noinput; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    depends_on:
      - db
    networks:
      - proxy_manager

networks:
  proxy_manager:
    name: proxy_manager