name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_HOST }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y ssh
      - name: SSH to EC2 instance and deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd Django-Portifolio
            git pull
            docker-compose up -d
