name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_HOST }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY_PEM: ${{ secrets.SSH_PRIVATE_KEY_PEM }}

    steps:
      - name: Save SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY_PEM" > ~/.ssh/id_rsa.pem
          chmod 600 ~/.ssh/id_rsa.pem

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: SSH to EC2 instance and deploy changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key_path: ~/.ssh/id_rsa.pem
          port: 22
          script: |
            cd Django-Portifolio
            git pull
            docker-compose up -d
